// <auto-generated />
using System;
using BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206072219_GTNH")]
    partial class GTNH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ApplicationUserChat", b =>
                {
                    b.Property<int>("ChatIdsChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIdsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatIdsChatId", "UserIdsId");

                    b.HasIndex("UserIdsId");

                    b.ToTable("ApplicationUserChat");
                });

            modelBuilder.Entity("ApplicationUserHobby", b =>
                {
                    b.Property<int>("HobbiesHobbyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsersId")
                        .HasColumnType("TEXT");

                    b.HasKey("HobbiesHobbyId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationUserHobby");
                });

            modelBuilder.Entity("BlazorServer.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("BcitEmail")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BcitEmailIsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FavoriteHobby1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FavoriteHobby2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FavoriteHobby3Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BcitEmail")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FavoriteHobby1Id");

                    b.HasIndex("FavoriteHobby2Id");

                    b.HasIndex("FavoriteHobby3Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlazorServer.Data.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("BlazorServer.Data.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbyId = 1,
                            HobbyName = "🪂Air sports"
                        },
                        new
                        {
                            HobbyId = 2,
                            HobbyName = "🔫Airsoft"
                        },
                        new
                        {
                            HobbyId = 3,
                            HobbyName = "🪨Amateur geology"
                        },
                        new
                        {
                            HobbyId = 4,
                            HobbyName = "🎢Amusement park visiting"
                        },
                        new
                        {
                            HobbyId = 5,
                            HobbyName = "🏹Archery"
                        },
                        new
                        {
                            HobbyId = 6,
                            HobbyName = "🧽Auto detailing"
                        },
                        new
                        {
                            HobbyId = 7,
                            HobbyName = "🚗Automobilism"
                        },
                        new
                        {
                            HobbyId = 8,
                            HobbyName = "🔭Astronomy"
                        },
                        new
                        {
                            HobbyId = 9,
                            HobbyName = "🎒Backpacking"
                        },
                        new
                        {
                            HobbyId = 10,
                            HobbyName = "🏸Badminton"
                        },
                        new
                        {
                            HobbyId = 11,
                            HobbyName = "🪂BASE jumping"
                        },
                        new
                        {
                            HobbyId = 12,
                            HobbyName = "⚾Baseball"
                        },
                        new
                        {
                            HobbyId = 13,
                            HobbyName = "🏀Basketball"
                        },
                        new
                        {
                            HobbyId = 14,
                            HobbyName = "🏖️Beachcombing"
                        },
                        new
                        {
                            HobbyId = 15,
                            HobbyName = "🐝Beekeeping"
                        },
                        new
                        {
                            HobbyId = 16,
                            HobbyName = "🐦Birdwatching"
                        },
                        new
                        {
                            HobbyId = 17,
                            HobbyName = "⚒️Blacksmithing"
                        },
                        new
                        {
                            HobbyId = 18,
                            HobbyName = "🚴‍♂️BMX"
                        },
                        new
                        {
                            HobbyId = 19,
                            HobbyName = "🏄‍♂️Board sports"
                        },
                        new
                        {
                            HobbyId = 20,
                            HobbyName = "🏋️Bodybuilding"
                        },
                        new
                        {
                            HobbyId = 21,
                            HobbyName = "🚌Bus riding"
                        },
                        new
                        {
                            HobbyId = 22,
                            HobbyName = "🏕️Camping"
                        },
                        new
                        {
                            HobbyId = 23,
                            HobbyName = "🛶Canoeing"
                        },
                        new
                        {
                            HobbyId = 24,
                            HobbyName = "🧗‍♂️Canyoning"
                        },
                        new
                        {
                            HobbyId = 25,
                            HobbyName = "🐦Carrier pigeons"
                        },
                        new
                        {
                            HobbyId = 26,
                            HobbyName = "🚗Car riding"
                        },
                        new
                        {
                            HobbyId = 27,
                            HobbyName = "⚙️Car tuning"
                        },
                        new
                        {
                            HobbyId = 28,
                            HobbyName = "🕳️Caving"
                        },
                        new
                        {
                            HobbyId = 29,
                            HobbyName = "🏙️City trip"
                        },
                        new
                        {
                            HobbyId = 30,
                            HobbyName = "🧗Climbing"
                        },
                        new
                        {
                            HobbyId = 31,
                            HobbyName = "🌱Composting"
                        },
                        new
                        {
                            HobbyId = 32,
                            HobbyName = "🏏Croquet"
                        },
                        new
                        {
                            HobbyId = 33,
                            HobbyName = "🚴Cycling"
                        },
                        new
                        {
                            HobbyId = 34,
                            HobbyName = "🐄Dairy Farming"
                        },
                        new
                        {
                            HobbyId = 35,
                            HobbyName = "🎩Dandyism"
                        },
                        new
                        {
                            HobbyId = 36,
                            HobbyName = "🎯Darts"
                        },
                        new
                        {
                            HobbyId = 37,
                            HobbyName = "🤾Dodgeball"
                        },
                        new
                        {
                            HobbyId = 38,
                            HobbyName = "🐕‍🦺Dog training"
                        },
                        new
                        {
                            HobbyId = 39,
                            HobbyName = "🐕Dog walking"
                        },
                        new
                        {
                            HobbyId = 40,
                            HobbyName = "🔮Dowsing"
                        },
                        new
                        {
                            HobbyId = 41,
                            HobbyName = "🚘Driving"
                        },
                        new
                        {
                            HobbyId = 42,
                            HobbyName = "🚜Farming"
                        },
                        new
                        {
                            HobbyId = 43,
                            HobbyName = "🎣Fishing"
                        },
                        new
                        {
                            HobbyId = 44,
                            HobbyName = "🏈Flag football"
                        },
                        new
                        {
                            HobbyId = 45,
                            HobbyName = "🌸Flower growing"
                        },
                        new
                        {
                            HobbyId = 46,
                            HobbyName = "✈️Flying"
                        },
                        new
                        {
                            HobbyId = 47,
                            HobbyName = "🥏Flying disc"
                        },
                        new
                        {
                            HobbyId = 48,
                            HobbyName = "🛩️Flying model planes"
                        },
                        new
                        {
                            HobbyId = 49,
                            HobbyName = "🍄Foraging"
                        },
                        new
                        {
                            HobbyId = 50,
                            HobbyName = "⛏️Fossicking"
                        },
                        new
                        {
                            HobbyId = 51,
                            HobbyName = "⚽Freestyle football"
                        },
                        new
                        {
                            HobbyId = 52,
                            HobbyName = "🍎Fruit picking"
                        },
                        new
                        {
                            HobbyId = 53,
                            HobbyName = "🌿Gardening"
                        },
                        new
                        {
                            HobbyId = 54,
                            HobbyName = "📍Geocaching"
                        },
                        new
                        {
                            HobbyId = 55,
                            HobbyName = "👻Ghost hunting"
                        },
                        new
                        {
                            HobbyId = 56,
                            HobbyName = "⛏️Gold prospecting"
                        },
                        new
                        {
                            HobbyId = 57,
                            HobbyName = "🎨Graffiti"
                        },
                        new
                        {
                            HobbyId = 58,
                            HobbyName = "⚽Groundhopping"
                        },
                        new
                        {
                            HobbyId = 59,
                            HobbyName = "🌱Guerrilla gardening"
                        },
                        new
                        {
                            HobbyId = 60,
                            HobbyName = "🤸Gymnastics"
                        },
                        new
                        {
                            HobbyId = 61,
                            HobbyName = "🤾‍♂️Handball"
                        },
                        new
                        {
                            HobbyId = 62,
                            HobbyName = "🌿Herbalism"
                        },
                        new
                        {
                            HobbyId = 63,
                            HobbyName = "🦎Herping"
                        },
                        new
                        {
                            HobbyId = 64,
                            HobbyName = "🚀High-power rocketry"
                        },
                        new
                        {
                            HobbyId = 65,
                            HobbyName = "🥾Hiking"
                        },
                        new
                        {
                            HobbyId = 66,
                            HobbyName = "🐴Hobby horsing"
                        },
                        new
                        {
                            HobbyId = 67,
                            HobbyName = "🕳️Hobby tunneling"
                        },
                        new
                        {
                            HobbyId = 68,
                            HobbyName = "🟠Hooping"
                        },
                        new
                        {
                            HobbyId = 69,
                            HobbyName = "🐎Horseback riding"
                        },
                        new
                        {
                            HobbyId = 70,
                            HobbyName = "🎯Hunting"
                        },
                        new
                        {
                            HobbyId = 71,
                            HobbyName = "🛼Inline skating"
                        },
                        new
                        {
                            HobbyId = 72,
                            HobbyName = "🏃Jogging"
                        },
                        new
                        {
                            HobbyId = 73,
                            HobbyName = "🪢Jumping rope"
                        },
                        new
                        {
                            HobbyId = 74,
                            HobbyName = "🏎️Karting"
                        },
                        new
                        {
                            HobbyId = 75,
                            HobbyName = "🛶Kayaking"
                        },
                        new
                        {
                            HobbyId = 76,
                            HobbyName = "🪁Kite flying"
                        },
                        new
                        {
                            HobbyId = 77,
                            HobbyName = "🏄‍♂️Kitesurfing"
                        },
                        new
                        {
                            HobbyId = 78,
                            HobbyName = "🥍Lacrosse"
                        },
                        new
                        {
                            HobbyId = 79,
                            HobbyName = "🧙‍♂️LARPing"
                        },
                        new
                        {
                            HobbyId = 80,
                            HobbyName = "📬Letterboxing"
                        },
                        new
                        {
                            HobbyId = 81,
                            HobbyName = "📸Lomography"
                        },
                        new
                        {
                            HobbyId = 82,
                            HobbyName = "🛹Longboarding"
                        },
                        new
                        {
                            HobbyId = 83,
                            HobbyName = "🥋Martial arts"
                        },
                        new
                        {
                            HobbyId = 84,
                            HobbyName = "🧲Magnet fishing"
                        },
                        new
                        {
                            HobbyId = 85,
                            HobbyName = "🪙Metal detecting"
                        },
                        new
                        {
                            HobbyId = 86,
                            HobbyName = "🏍️Motorcycling"
                        },
                        new
                        {
                            HobbyId = 87,
                            HobbyName = "🌦️Meteorology"
                        },
                        new
                        {
                            HobbyId = 88,
                            HobbyName = "🏁Motor sports"
                        },
                        new
                        {
                            HobbyId = 89,
                            HobbyName = "🚵Mountain biking"
                        },
                        new
                        {
                            HobbyId = 90,
                            HobbyName = "🗻Mountaineering"
                        },
                        new
                        {
                            HobbyId = 91,
                            HobbyName = "🏛️Museum visiting"
                        },
                        new
                        {
                            HobbyId = 92,
                            HobbyName = "🍄Mushroom hunting/mycology"
                        },
                        new
                        {
                            HobbyId = 93,
                            HobbyName = "🏐Netball"
                        },
                        new
                        {
                            HobbyId = 94,
                            HobbyName = "🐟Noodling"
                        },
                        new
                        {
                            HobbyId = 95,
                            HobbyName = "⛸️Nordic skating"
                        },
                        new
                        {
                            HobbyId = 96,
                            HobbyName = "🧭Orienteering"
                        },
                        new
                        {
                            HobbyId = 97,
                            HobbyName = "🔫Paintball"
                        },
                        new
                        {
                            HobbyId = 98,
                            HobbyName = "🪂Paragliding"
                        },
                        new
                        {
                            HobbyId = 99,
                            HobbyName = "🤸‍♂️Parkour"
                        },
                        new
                        {
                            HobbyId = 100,
                            HobbyName = "📸Photography"
                        },
                        new
                        {
                            HobbyId = 101,
                            HobbyName = "🥒Pickleball"
                        },
                        new
                        {
                            HobbyId = 102,
                            HobbyName = "🧺Picnicking"
                        },
                        new
                        {
                            HobbyId = 103,
                            HobbyName = "🎙️Podcast hosting"
                        },
                        new
                        {
                            HobbyId = 104,
                            HobbyName = "🐴Polo"
                        },
                        new
                        {
                            HobbyId = 105,
                            HobbyName = "🏋️‍♂️Powerlifting"
                        },
                        new
                        {
                            HobbyId = 106,
                            HobbyName = "🚌Public transport riding"
                        },
                        new
                        {
                            HobbyId = 107,
                            HobbyName = "🧘Qigong"
                        },
                        new
                        {
                            HobbyId = 108,
                            HobbyName = "🎮Radio-controlled model playing"
                        },
                        new
                        {
                            HobbyId = 109,
                            HobbyName = "🛶Rafting"
                        },
                        new
                        {
                            HobbyId = 110,
                            HobbyName = "🚂Railway journeys"
                        },
                        new
                        {
                            HobbyId = 111,
                            HobbyName = "🚆Railway modelling"
                        },
                        new
                        {
                            HobbyId = 112,
                            HobbyName = "🧗‍♂️Rappelling"
                        },
                        new
                        {
                            HobbyId = 113,
                            HobbyName = "🏰Renaissance fair"
                        },
                        new
                        {
                            HobbyId = 114,
                            HobbyName = "🔧Renovating"
                        },
                        new
                        {
                            HobbyId = 115,
                            HobbyName = "🚴‍♂️Road biking"
                        },
                        new
                        {
                            HobbyId = 116,
                            HobbyName = "🧗Rock climbing"
                        },
                        new
                        {
                            HobbyId = 117,
                            HobbyName = "🎨Rock painting"
                        },
                        new
                        {
                            HobbyId = 118,
                            HobbyName = "🛼Roller skating"
                        },
                        new
                        {
                            HobbyId = 119,
                            HobbyName = "🏐Roundnet"
                        },
                        new
                        {
                            HobbyId = 120,
                            HobbyName = "🏉Rugby"
                        },
                        new
                        {
                            HobbyId = 121,
                            HobbyName = "🏃Running"
                        },
                        new
                        {
                            HobbyId = 122,
                            HobbyName = "🦁Safari"
                        },
                        new
                        {
                            HobbyId = 123,
                            HobbyName = "⛵Sailing"
                        },
                        new
                        {
                            HobbyId = 124,
                            HobbyName = "🏖️Sand art"
                        },
                        new
                        {
                            HobbyId = 125,
                            HobbyName = "⚜️Scouting"
                        },
                        new
                        {
                            HobbyId = 126,
                            HobbyName = "🤿Scuba diving"
                        },
                        new
                        {
                            HobbyId = 127,
                            HobbyName = "🚣Sculling or rowing"
                        },
                        new
                        {
                            HobbyId = 128,
                            HobbyName = "🔫Shooting"
                        },
                        new
                        {
                            HobbyId = 129,
                            HobbyName = "🛍️Shopping"
                        },
                        new
                        {
                            HobbyId = 130,
                            HobbyName = "🟦Shuffleboard"
                        },
                        new
                        {
                            HobbyId = 131,
                            HobbyName = "🛹Skateboarding"
                        },
                        new
                        {
                            HobbyId = 132,
                            HobbyName = "🎿Skiing"
                        },
                        new
                        {
                            HobbyId = 133,
                            HobbyName = "🏄‍♂️Skimboarding"
                        },
                        new
                        {
                            HobbyId = 134,
                            HobbyName = "🪂Skydiving"
                        },
                        new
                        {
                            HobbyId = 135,
                            HobbyName = "🧵Slacklining"
                        },
                        new
                        {
                            HobbyId = 136,
                            HobbyName = "🛷Sledding"
                        },
                        new
                        {
                            HobbyId = 137,
                            HobbyName = "🤿Snorkeling"
                        },
                        new
                        {
                            HobbyId = 138,
                            HobbyName = "🏂Snowboarding"
                        },
                        new
                        {
                            HobbyId = 139,
                            HobbyName = "❄️Snowmobiling"
                        },
                        new
                        {
                            HobbyId = 140,
                            HobbyName = "🥾Snowshoeing"
                        },
                        new
                        {
                            HobbyId = 141,
                            HobbyName = "⚽Soccer"
                        },
                        new
                        {
                            HobbyId = 142,
                            HobbyName = "🪨Stone skipping"
                        },
                        new
                        {
                            HobbyId = 143,
                            HobbyName = "🌪️Storm chasing"
                        },
                        new
                        {
                            HobbyId = 144,
                            HobbyName = "🌞Sun bathing"
                        },
                        new
                        {
                            HobbyId = 145,
                            HobbyName = "🏄Surfing"
                        },
                        new
                        {
                            HobbyId = 146,
                            HobbyName = "🗡️Survivalism"
                        },
                        new
                        {
                            HobbyId = 147,
                            HobbyName = "🏊Swimming"
                        },
                        new
                        {
                            HobbyId = 148,
                            HobbyName = "🏓Table tennis playing"
                        },
                        new
                        {
                            HobbyId = 149,
                            HobbyName = "🥋Taekwondo"
                        },
                        new
                        {
                            HobbyId = 150,
                            HobbyName = "🧘‍♂️Tai chi"
                        },
                        new
                        {
                            HobbyId = 151,
                            HobbyName = "🎾Tennis"
                        },
                        new
                        {
                            HobbyId = 152,
                            HobbyName = "🥾Thru-hiking"
                        },
                        new
                        {
                            HobbyId = 153,
                            HobbyName = "🌳Topiary"
                        },
                        new
                        {
                            HobbyId = 154,
                            HobbyName = "🌍Tourism"
                        },
                        new
                        {
                            HobbyId = 155,
                            HobbyName = "🏬Trade fair visiting"
                        },
                        new
                        {
                            HobbyId = 156,
                            HobbyName = "✈️Travel"
                        },
                        new
                        {
                            HobbyId = 157,
                            HobbyName = "🚴‍♀️Unicycling"
                        },
                        new
                        {
                            HobbyId = 158,
                            HobbyName = "🏚️Urban exploration"
                        },
                        new
                        {
                            HobbyId = 159,
                            HobbyName = "🏖️Vacation"
                        },
                        new
                        {
                            HobbyId = 160,
                            HobbyName = "🥕Vegetable farming"
                        },
                        new
                        {
                            HobbyId = 161,
                            HobbyName = "🔧Vehicle restoration"
                        },
                        new
                        {
                            HobbyId = 162,
                            HobbyName = "🎥Videography"
                        },
                        new
                        {
                            HobbyId = 163,
                            HobbyName = "🏐Volleyball"
                        },
                        new
                        {
                            HobbyId = 164,
                            HobbyName = "🤝Volunteering"
                        },
                        new
                        {
                            HobbyId = 165,
                            HobbyName = "🚶Walking"
                        },
                        new
                        {
                            HobbyId = 166,
                            HobbyName = "🌊Water sports"
                        },
                        new
                        {
                            HobbyId = 167,
                            HobbyName = "🦓Zoo visiting"
                        },
                        new
                        {
                            HobbyId = 168,
                            HobbyName = "🏺Archaeology"
                        },
                        new
                        {
                            HobbyId = 169,
                            HobbyName = "🏛️Architecture"
                        },
                        new
                        {
                            HobbyId = 170,
                            HobbyName = "🔭Astronomy"
                        },
                        new
                        {
                            HobbyId = 171,
                            HobbyName = "🎞️Animation"
                        },
                        new
                        {
                            HobbyId = 172,
                            HobbyName = "🚀Aerospace"
                        },
                        new
                        {
                            HobbyId = 173,
                            HobbyName = "🧬Biology"
                        },
                        new
                        {
                            HobbyId = 174,
                            HobbyName = "🌿Botany"
                        },
                        new
                        {
                            HobbyId = 175,
                            HobbyName = "💼Business"
                        },
                        new
                        {
                            HobbyId = 176,
                            HobbyName = "⚗️Chemistry"
                        },
                        new
                        {
                            HobbyId = 177,
                            HobbyName = "🚀Entrepreneurship"
                        },
                        new
                        {
                            HobbyId = 178,
                            HobbyName = "💰Finance"
                        },
                        new
                        {
                            HobbyId = 179,
                            HobbyName = "🗺️Geography"
                        },
                        new
                        {
                            HobbyId = 180,
                            HobbyName = "📜History"
                        },
                        new
                        {
                            HobbyId = 181,
                            HobbyName = "🗣️Linguistics"
                        },
                        new
                        {
                            HobbyId = 182,
                            HobbyName = "📚Literature"
                        },
                        new
                        {
                            HobbyId = 183,
                            HobbyName = "➗Mathematics"
                        },
                        new
                        {
                            HobbyId = 184,
                            HobbyName = "🩺Medical science"
                        },
                        new
                        {
                            HobbyId = 185,
                            HobbyName = "🦠Microbiology"
                        },
                        new
                        {
                            HobbyId = 186,
                            HobbyName = "🍄Mycology"
                        },
                        new
                        {
                            HobbyId = 187,
                            HobbyName = "🐜Myrmecology"
                        },
                        new
                        {
                            HobbyId = 188,
                            HobbyName = "🧠Neuroscience"
                        },
                        new
                        {
                            HobbyId = 189,
                            HobbyName = "🤔Philosophy"
                        },
                        new
                        {
                            HobbyId = 190,
                            HobbyName = "🔬Physics"
                        },
                        new
                        {
                            HobbyId = 191,
                            HobbyName = "🧠Psychology"
                        },
                        new
                        {
                            HobbyId = 192,
                            HobbyName = "🚆Railway studies"
                        },
                        new
                        {
                            HobbyId = 193,
                            HobbyName = "⛪Religious studies"
                        },
                        new
                        {
                            HobbyId = 194,
                            HobbyName = "🔎Research"
                        },
                        new
                        {
                            HobbyId = 195,
                            HobbyName = "🧪Science and technology studies"
                        },
                        new
                        {
                            HobbyId = 196,
                            HobbyName = "🌍Social studies"
                        },
                        new
                        {
                            HobbyId = 197,
                            HobbyName = "👥Sociology"
                        },
                        new
                        {
                            HobbyId = 198,
                            HobbyName = "🏅Sports science"
                        },
                        new
                        {
                            HobbyId = 199,
                            HobbyName = "✍️Story writing"
                        },
                        new
                        {
                            HobbyId = 200,
                            HobbyName = "🧬Life science"
                        },
                        new
                        {
                            HobbyId = 201,
                            HobbyName = "📚Teaching"
                        },
                        new
                        {
                            HobbyId = 202,
                            HobbyName = "💻Web design"
                        },
                        new
                        {
                            HobbyId = 203,
                            HobbyName = "🛠️Engineering"
                        },
                        new
                        {
                            HobbyId = 204,
                            HobbyName = "⚖️Jurisprudential"
                        },
                        new
                        {
                            HobbyId = 205,
                            HobbyName = "📰Publishing"
                        },
                        new
                        {
                            HobbyId = 206,
                            HobbyName = "📝Wikipedia editing"
                        },
                        new
                        {
                            HobbyId = 207,
                            HobbyName = "🧸Action figure"
                        },
                        new
                        {
                            HobbyId = 208,
                            HobbyName = "🏺Antiquing"
                        },
                        new
                        {
                            HobbyId = 209,
                            HobbyName = "🐜Ant-keeping"
                        },
                        new
                        {
                            HobbyId = 210,
                            HobbyName = "🖼️Art collecting"
                        },
                        new
                        {
                            HobbyId = 211,
                            HobbyName = "📚Book collecting"
                        },
                        new
                        {
                            HobbyId = 212,
                            HobbyName = "🔘Button collecting"
                        },
                        new
                        {
                            HobbyId = 213,
                            HobbyName = "🃏Cartophily (card collecting)"
                        },
                        new
                        {
                            HobbyId = 214,
                            HobbyName = "🪙Coin collecting"
                        },
                        new
                        {
                            HobbyId = 215,
                            HobbyName = "📚Comic book collecting"
                        },
                        new
                        {
                            HobbyId = 216,
                            HobbyName = "💿Compact discs"
                        },
                        new
                        {
                            HobbyId = 217,
                            HobbyName = "🔮Crystals"
                        },
                        new
                        {
                            HobbyId = 218,
                            HobbyName = "💌Deltiology (postcard collecting)"
                        },
                        new
                        {
                            HobbyId = 219,
                            HobbyName = "🚗Die-cast toy"
                        },
                        new
                        {
                            HobbyId = 220,
                            HobbyName = "💾Digital hoarding"
                        },
                        new
                        {
                            HobbyId = 221,
                            HobbyName = "🪆Dolls"
                        },
                        new
                        {
                            HobbyId = 222,
                            HobbyName = "🧪Element collecting"
                        },
                        new
                        {
                            HobbyId = 223,
                            HobbyName = "📜Ephemera collecting"
                        },
                        new
                        {
                            HobbyId = 224,
                            HobbyName = "🎬Films"
                        },
                        new
                        {
                            HobbyId = 225,
                            HobbyName = "🖐️Fingerprint collecting"
                        },
                        new
                        {
                            HobbyId = 226,
                            HobbyName = "📞Fusilately (phonecard collecting)"
                        },
                        new
                        {
                            HobbyId = 227,
                            HobbyName = "🔪Knife collecting"
                        },
                        new
                        {
                            HobbyId = 228,
                            HobbyName = "📍Lapel pins"
                        },
                        new
                        {
                            HobbyId = 229,
                            HobbyName = "🎟️Lotology (lottery ticket collecting)"
                        },
                        new
                        {
                            HobbyId = 230,
                            HobbyName = "🎞️Movie memorabilia collecting"
                        },
                        new
                        {
                            HobbyId = 231,
                            HobbyName = "💵Notaphily (banknote collecting)"
                        },
                        new
                        {
                            HobbyId = 232,
                            HobbyName = "🌸Perfume"
                        },
                        new
                        {
                            HobbyId = 233,
                            HobbyName = "📮Philately"
                        },
                        new
                        {
                            HobbyId = 234,
                            HobbyName = "🕯️Phillumeny"
                        },
                        new
                        {
                            HobbyId = 235,
                            HobbyName = "🎮Radio-controlled model collecting"
                        },
                        new
                        {
                            HobbyId = 236,
                            HobbyName = "🚆Rail transport modelling"
                        },
                        new
                        {
                            HobbyId = 237,
                            HobbyName = "💽Record collecting"
                        },
                        new
                        {
                            HobbyId = 238,
                            HobbyName = "🪨Rock tumbling"
                        },
                        new
                        {
                            HobbyId = 239,
                            HobbyName = "🏁Scutelliphily"
                        },
                        new
                        {
                            HobbyId = 240,
                            HobbyName = "👟Shoes"
                        },
                        new
                        {
                            HobbyId = 241,
                            HobbyName = "🏎️Slot car"
                        },
                        new
                        {
                            HobbyId = 242,
                            HobbyName = "🏆Sports memorabilia"
                        },
                        new
                        {
                            HobbyId = 243,
                            HobbyName = "📮Stamp collecting"
                        },
                        new
                        {
                            HobbyId = 244,
                            HobbyName = "🧸Stuffed toy collecting"
                        },
                        new
                        {
                            HobbyId = 245,
                            HobbyName = "🫖Tea bag collecting"
                        },
                        new
                        {
                            HobbyId = 246,
                            HobbyName = "🎫Ticket collecting"
                        },
                        new
                        {
                            HobbyId = 247,
                            HobbyName = "🗺️Transit map collecting"
                        },
                        new
                        {
                            HobbyId = 248,
                            HobbyName = "🎮Video game collecting"
                        },
                        new
                        {
                            HobbyId = 249,
                            HobbyName = "🚗Vintage cars"
                        },
                        new
                        {
                            HobbyId = 250,
                            HobbyName = "👗Vintage clothing"
                        },
                        new
                        {
                            HobbyId = 251,
                            HobbyName = "📀Vinyl records"
                        },
                        new
                        {
                            HobbyId = 252,
                            HobbyName = "🏺Antiquities"
                        },
                        new
                        {
                            HobbyId = 253,
                            HobbyName = "🔊Auto audiophilia"
                        },
                        new
                        {
                            HobbyId = 254,
                            HobbyName = "🌸Flower collecting and pressing"
                        },
                        new
                        {
                            HobbyId = 255,
                            HobbyName = "🦴Fossil hunting"
                        },
                        new
                        {
                            HobbyId = 256,
                            HobbyName = "🪳Insect collecting"
                        },
                        new
                        {
                            HobbyId = 257,
                            HobbyName = "🍃Leaves"
                        },
                        new
                        {
                            HobbyId = 258,
                            HobbyName = "🧲Magnet fishing"
                        },
                        new
                        {
                            HobbyId = 259,
                            HobbyName = "🪙Metal detecting"
                        },
                        new
                        {
                            HobbyId = 260,
                            HobbyName = "⛏️Mineral collecting"
                        },
                        new
                        {
                            HobbyId = 261,
                            HobbyName = "🪨Rock balancing"
                        },
                        new
                        {
                            HobbyId = 262,
                            HobbyName = "🟦Sea glass collecting"
                        },
                        new
                        {
                            HobbyId = 263,
                            HobbyName = "🐚Seashell collecting"
                        },
                        new
                        {
                            HobbyId = 264,
                            HobbyName = "🪨Stone collecting"
                        },
                        new
                        {
                            HobbyId = 265,
                            HobbyName = "🏒Air hockey"
                        },
                        new
                        {
                            HobbyId = 266,
                            HobbyName = "🐕Animal fancy"
                        },
                        new
                        {
                            HobbyId = 267,
                            HobbyName = "🪓Axe throwing"
                        },
                        new
                        {
                            HobbyId = 268,
                            HobbyName = "🎲Backgammon"
                        },
                        new
                        {
                            HobbyId = 269,
                            HobbyName = "🏸Badminton"
                        },
                        new
                        {
                            HobbyId = 270,
                            HobbyName = "🧁Baking"
                        },
                        new
                        {
                            HobbyId = 271,
                            HobbyName = "🩰Ballet dancing"
                        },
                        new
                        {
                            HobbyId = 272,
                            HobbyName = "💃Ballroom dancing"
                        },
                        new
                        {
                            HobbyId = 273,
                            HobbyName = "🎗️Baton twirling"
                        },
                        new
                        {
                            HobbyId = 274,
                            HobbyName = "👑Beauty pageants"
                        },
                        new
                        {
                            HobbyId = 275,
                            HobbyName = "🎱Billiards"
                        },
                        new
                        {
                            HobbyId = 276,
                            HobbyName = "📘Book folding"
                        },
                        new
                        {
                            HobbyId = 277,
                            HobbyName = "🎳Bowling"
                        },
                        new
                        {
                            HobbyId = 278,
                            HobbyName = "🥊Boxing"
                        },
                        new
                        {
                            HobbyId = 279,
                            HobbyName = "🃏Bridge"
                        },
                        new
                        {
                            HobbyId = 280,
                            HobbyName = "🍳Cooking"
                        },
                        new
                        {
                            HobbyId = 281,
                            HobbyName = "♟️Checkers (draughts)"
                        },
                        new
                        {
                            HobbyId = 282,
                            HobbyName = "📣Cheerleading"
                        },
                        new
                        {
                            HobbyId = 283,
                            HobbyName = "♟️Chess"
                        },
                        new
                        {
                            HobbyId = 284,
                            HobbyName = "🚩Color guard"
                        },
                        new
                        {
                            HobbyId = 285,
                            HobbyName = "♣️Cribbage"
                        },
                        new
                        {
                            HobbyId = 286,
                            HobbyName = "🥌Curling"
                        },
                        new
                        {
                            HobbyId = 287,
                            HobbyName = "💃Dancing"
                        },
                        new
                        {
                            HobbyId = 288,
                            HobbyName = "🎯Darts"
                        },
                        new
                        {
                            HobbyId = 289,
                            HobbyName = "🗣️Debate"
                        },
                        new
                        {
                            HobbyId = 290,
                            HobbyName = "🁬Dominoes"
                        },
                        new
                        {
                            HobbyId = 291,
                            HobbyName = "🍽️Eating"
                        },
                        new
                        {
                            HobbyId = 292,
                            HobbyName = "🎮Esports"
                        },
                        new
                        {
                            HobbyId = 293,
                            HobbyName = "🤺Fencing"
                        },
                        new
                        {
                            HobbyId = 294,
                            HobbyName = "⛸️Figure Skating"
                        },
                        new
                        {
                            HobbyId = 295,
                            HobbyName = "⚫Go"
                        },
                        new
                        {
                            HobbyId = 296,
                            HobbyName = "🤸Gymnastics"
                        },
                        new
                        {
                            HobbyId = 297,
                            HobbyName = "🏒Ice hockey"
                        },
                        new
                        {
                            HobbyId = 298,
                            HobbyName = "⛸️Ice skating"
                        },
                        new
                        {
                            HobbyId = 299,
                            HobbyName = "🥋Judo"
                        },
                        new
                        {
                            HobbyId = 300,
                            HobbyName = "🥋Jujitsu"
                        },
                        new
                        {
                            HobbyId = 301,
                            HobbyName = "🤼Kabaddi"
                        },
                        new
                        {
                            HobbyId = 302,
                            HobbyName = "🔠Knowledge/word games"
                        },
                        new
                        {
                            HobbyId = 303,
                            HobbyName = "🔫Laser tag"
                        },
                        new
                        {
                            HobbyId = 304,
                            HobbyName = "✨Magic"
                        },
                        new
                        {
                            HobbyId = 305,
                            HobbyName = "🀄Mahjong"
                        },
                        new
                        {
                            HobbyId = 306,
                            HobbyName = "🔵Marbles"
                        },
                        new
                        {
                            HobbyId = 307,
                            HobbyName = "🥋Martial arts"
                        },
                        new
                        {
                            HobbyId = 308,
                            HobbyName = "🏎️Model racing"
                        },
                        new
                        {
                            HobbyId = 309,
                            HobbyName = "🌐Model United Nations"
                        },
                        new
                        {
                            HobbyId = 310,
                            HobbyName = "🎰Pinball"
                        },
                        new
                        {
                            HobbyId = 311,
                            HobbyName = "🃏Poker"
                        },
                        new
                        {
                            HobbyId = 312,
                            HobbyName = "💃Pole dancing"
                        },
                        new
                        {
                            HobbyId = 313,
                            HobbyName = "🎱Pool"
                        },
                        new
                        {
                            HobbyId = 314,
                            HobbyName = "🎮Radio-controlled model playing"
                        },
                        new
                        {
                            HobbyId = 315,
                            HobbyName = "🎲Role-playing games"
                        },
                        new
                        {
                            HobbyId = 316,
                            HobbyName = "🧵Rughooking"
                        },
                        new
                        {
                            HobbyId = 317,
                            HobbyName = "♟️Shogi"
                        },
                        new
                        {
                            HobbyId = 318,
                            HobbyName = "🏎️Slot car racing"
                        },
                        new
                        {
                            HobbyId = 319,
                            HobbyName = "🧩Speedcubing"
                        },
                        new
                        {
                            HobbyId = 320,
                            HobbyName = "🧱Sport stacking"
                        },
                        new
                        {
                            HobbyId = 321,
                            HobbyName = "⚽Table football"
                        },
                        new
                        {
                            HobbyId = 322,
                            HobbyName = "🏓Table tennis"
                        },
                        new
                        {
                            HobbyId = 323,
                            HobbyName = "🏐Volleyball"
                        },
                        new
                        {
                            HobbyId = 324,
                            HobbyName = "🎮Video gaming"
                        },
                        new
                        {
                            HobbyId = 325,
                            HobbyName = "🕶️VR gaming"
                        },
                        new
                        {
                            HobbyId = 326,
                            HobbyName = "🏋️Weightlifting"
                        },
                        new
                        {
                            HobbyId = 327,
                            HobbyName = "🤼Wrestling"
                        },
                        new
                        {
                            HobbyId = 328,
                            HobbyName = "🔫Airsoft"
                        },
                        new
                        {
                            HobbyId = 329,
                            HobbyName = "🏹Archery"
                        },
                        new
                        {
                            HobbyId = 330,
                            HobbyName = "⚽Association football"
                        },
                        new
                        {
                            HobbyId = 331,
                            HobbyName = "🏉Australian rules football"
                        },
                        new
                        {
                            HobbyId = 332,
                            HobbyName = "🏎️Auto racing"
                        },
                        new
                        {
                            HobbyId = 333,
                            HobbyName = "⚾Baseball"
                        },
                        new
                        {
                            HobbyId = 334,
                            HobbyName = "🏖️Beach volleyball"
                        },
                        new
                        {
                            HobbyId = 335,
                            HobbyName = "🕺Breakdancing"
                        },
                        new
                        {
                            HobbyId = 336,
                            HobbyName = "🥋Capoeira"
                        },
                        new
                        {
                            HobbyId = 337,
                            HobbyName = "🧗Climbing"
                        },
                        new
                        {
                            HobbyId = 338,
                            HobbyName = "🟩Cornhole"
                        },
                        new
                        {
                            HobbyId = 339,
                            HobbyName = "🏏Cricket"
                        },
                        new
                        {
                            HobbyId = 340,
                            HobbyName = "🏏Croquet"
                        },
                        new
                        {
                            HobbyId = 341,
                            HobbyName = "🚴Cycling"
                        },
                        new
                        {
                            HobbyId = 342,
                            HobbyName = "🥏Disc golf"
                        },
                        new
                        {
                            HobbyId = 343,
                            HobbyName = "🐕Dog sport"
                        },
                        new
                        {
                            HobbyId = 344,
                            HobbyName = "🐎Equestrianism"
                        },
                        new
                        {
                            HobbyId = 345,
                            HobbyName = "🪖Exhibition drill"
                        },
                        new
                        {
                            HobbyId = 346,
                            HobbyName = "🏑Field hockey"
                        },
                        new
                        {
                            HobbyId = 347,
                            HobbyName = "⛸️Figure skating"
                        },
                        new
                        {
                            HobbyId = 348,
                            HobbyName = "🎣Fishing"
                        },
                        new
                        {
                            HobbyId = 349,
                            HobbyName = "💪Fitness"
                        },
                        new
                        {
                            HobbyId = 350,
                            HobbyName = "🥏Footbag"
                        },
                        new
                        {
                            HobbyId = 351,
                            HobbyName = "🥏Frisbee"
                        },
                        new
                        {
                            HobbyId = 352,
                            HobbyName = "🏉Rugby league football"
                        },
                        new
                        {
                            HobbyId = 353,
                            HobbyName = "🚣Sculling or rowing"
                        },
                        new
                        {
                            HobbyId = 354,
                            HobbyName = "🎯Shooting sports"
                        },
                        new
                        {
                            HobbyId = 355,
                            HobbyName = "🛹Skateboarding"
                        },
                        new
                        {
                            HobbyId = 356,
                            HobbyName = "🎿Skiing"
                        },
                        new
                        {
                            HobbyId = 357,
                            HobbyName = "🐕‍🦺Sled dog racing"
                        },
                        new
                        {
                            HobbyId = 358,
                            HobbyName = "🥎Softball"
                        },
                        new
                        {
                            HobbyId = 359,
                            HobbyName = "⛸️Speed skating"
                        },
                        new
                        {
                            HobbyId = 360,
                            HobbyName = "🎾Squash"
                        },
                        new
                        {
                            HobbyId = 361,
                            HobbyName = "🏄Surfing"
                        },
                        new
                        {
                            HobbyId = 362,
                            HobbyName = "🏊Swimming"
                        },
                        new
                        {
                            HobbyId = 363,
                            HobbyName = "🏓Table tennis"
                        },
                        new
                        {
                            HobbyId = 364,
                            HobbyName = "🎾Tennis"
                        },
                        new
                        {
                            HobbyId = 365,
                            HobbyName = "🎾Tennis polo"
                        },
                        new
                        {
                            HobbyId = 366,
                            HobbyName = "🚗Tether car"
                        },
                        new
                        {
                            HobbyId = 367,
                            HobbyName = "⛸️Tour skating"
                        },
                        new
                        {
                            HobbyId = 368,
                            HobbyName = "🌍Tourism"
                        },
                        new
                        {
                            HobbyId = 369,
                            HobbyName = "🎯Trapshooting"
                        },
                        new
                        {
                            HobbyId = 370,
                            HobbyName = "🏊‍♂️Triathlon"
                        },
                        new
                        {
                            HobbyId = 371,
                            HobbyName = "🥏Ultimate frisbee"
                        },
                        new
                        {
                            HobbyId = 372,
                            HobbyName = "🏐Volleyball"
                        },
                        new
                        {
                            HobbyId = 373,
                            HobbyName = "🤽Water polo"
                        },
                        new
                        {
                            HobbyId = 374,
                            HobbyName = "🏌️Golfing"
                        },
                        new
                        {
                            HobbyId = 375,
                            HobbyName = "🤾Handball"
                        },
                        new
                        {
                            HobbyId = 376,
                            HobbyName = "🐎Horseback riding"
                        },
                        new
                        {
                            HobbyId = 377,
                            HobbyName = "🐴Horsemanship"
                        },
                        new
                        {
                            HobbyId = 378,
                            HobbyName = "🐎Horseshoes"
                        },
                        new
                        {
                            HobbyId = 379,
                            HobbyName = "🛶Iceboat racing"
                        },
                        new
                        {
                            HobbyId = 380,
                            HobbyName = "🎯Jukskei"
                        },
                        new
                        {
                            HobbyId = 381,
                            HobbyName = "🏎️Kart racing"
                        },
                        new
                        {
                            HobbyId = 382,
                            HobbyName = "🔪Knife throwing"
                        },
                        new
                        {
                            HobbyId = 383,
                            HobbyName = "🥍Lacrosse"
                        },
                        new
                        {
                            HobbyId = 384,
                            HobbyName = "🛹Longboarding"
                        },
                        new
                        {
                            HobbyId = 385,
                            HobbyName = "🏃‍♂️Long-distance running"
                        },
                        new
                        {
                            HobbyId = 386,
                            HobbyName = "🥁Marching band"
                        },
                        new
                        {
                            HobbyId = 387,
                            HobbyName = "⛳Mini Golf"
                        },
                        new
                        {
                            HobbyId = 388,
                            HobbyName = "🛩️Model aircraft"
                        },
                        new
                        {
                            HobbyId = 389,
                            HobbyName = "🧭Orienteering"
                        },
                        new
                        {
                            HobbyId = 390,
                            HobbyName = "🥒Pickleball"
                        },
                        new
                        {
                            HobbyId = 391,
                            HobbyName = "🚤Powerboat racing"
                        },
                        new
                        {
                            HobbyId = 392,
                            HobbyName = "🏆Quidditch"
                        },
                        new
                        {
                            HobbyId = 393,
                            HobbyName = "🚶‍♂️Race walking"
                        },
                        new
                        {
                            HobbyId = 394,
                            HobbyName = "🎾Racquetball"
                        },
                        new
                        {
                            HobbyId = 395,
                            HobbyName = "🚗Radio-controlled car racing"
                        },
                        new
                        {
                            HobbyId = 396,
                            HobbyName = "🎮Radio-controlled model playing"
                        },
                        new
                        {
                            HobbyId = 397,
                            HobbyName = "🛼Roller derby"
                        },
                        new
                        {
                            HobbyId = 398,
                            HobbyName = "🎧Audiophile"
                        },
                        new
                        {
                            HobbyId = 399,
                            HobbyName = "🐜Ant farming"
                        },
                        new
                        {
                            HobbyId = 400,
                            HobbyName = "🐠Fishkeeping"
                        },
                        new
                        {
                            HobbyId = 401,
                            HobbyName = "📘Learning"
                        },
                        new
                        {
                            HobbyId = 402,
                            HobbyName = "🧘Meditation"
                        },
                        new
                        {
                            HobbyId = 403,
                            HobbyName = "🔬Microscopy"
                        },
                        new
                        {
                            HobbyId = 404,
                            HobbyName = "📖Reading"
                        },
                        new
                        {
                            HobbyId = 405,
                            HobbyName = "🔎Research"
                        },
                        new
                        {
                            HobbyId = 406,
                            HobbyName = "📻Shortwave listening"
                        },
                        new
                        {
                            HobbyId = 407,
                            HobbyName = "🛩️Aircraft spotting"
                        },
                        new
                        {
                            HobbyId = 408,
                            HobbyName = "🔭Amateur astronomy"
                        },
                        new
                        {
                            HobbyId = 409,
                            HobbyName = "🐝Beekeeping"
                        },
                        new
                        {
                            HobbyId = 410,
                            HobbyName = "📊Benchmarking"
                        },
                        new
                        {
                            HobbyId = 411,
                            HobbyName = "🐦Birdwatching"
                        },
                        new
                        {
                            HobbyId = 412,
                            HobbyName = "🚌Bus spotting"
                        },
                        new
                        {
                            HobbyId = 413,
                            HobbyName = "👀People-watching"
                        },
                        new
                        {
                            HobbyId = 414,
                            HobbyName = "📸Photography"
                        },
                        new
                        {
                            HobbyId = 415,
                            HobbyName = "📡Satellite watching"
                        },
                        new
                        {
                            HobbyId = 416,
                            HobbyName = "🚆Trainspotting"
                        },
                        new
                        {
                            HobbyId = 417,
                            HobbyName = "🐋Whale watching"
                        },
                        new
                        {
                            HobbyId = 418,
                            HobbyName = "🦋Butterfly watching"
                        },
                        new
                        {
                            HobbyId = 419,
                            HobbyName = "📍Geocaching"
                        },
                        new
                        {
                            HobbyId = 420,
                            HobbyName = "👀Gongoozling"
                        },
                        new
                        {
                            HobbyId = 421,
                            HobbyName = "🦎Herping"
                        },
                        new
                        {
                            HobbyId = 422,
                            HobbyName = "🥾Hiking/backpacking"
                        },
                        new
                        {
                            HobbyId = 423,
                            HobbyName = "🌦️Meteorology"
                        },
                        new
                        {
                            HobbyId = 424,
                            HobbyName = "💀Quake"
                        },
                        new
                        {
                            HobbyId = 425,
                            HobbyName = "🧭GT: NH"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatID");

                    b.HasIndex("SentUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationUserChat", b =>
                {
                    b.HasOne("BlazorServer.Data.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatIdsChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserIdsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserHobby", b =>
                {
                    b.HasOne("BlazorServer.Data.Hobby", null)
                        .WithMany()
                        .HasForeignKey("HobbiesHobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorServer.Data.ApplicationUser", b =>
                {
                    b.HasOne("BlazorServer.Data.Hobby", "FavoriteHobby1")
                        .WithMany("Favorite1Users")
                        .HasForeignKey("FavoriteHobby1Id");

                    b.HasOne("BlazorServer.Data.Hobby", "FavoriteHobby2")
                        .WithMany("Favorite2Users")
                        .HasForeignKey("FavoriteHobby2Id");

                    b.HasOne("BlazorServer.Data.Hobby", "FavoriteHobby3")
                        .WithMany("Favorite3Users")
                        .HasForeignKey("FavoriteHobby3Id");

                    b.Navigation("FavoriteHobby1");

                    b.Navigation("FavoriteHobby2");

                    b.Navigation("FavoriteHobby3");
                });

            modelBuilder.Entity("BlazorServer.Data.Message", b =>
                {
                    b.HasOne("BlazorServer.Data.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.Data.ApplicationUser", "SentUser")
                        .WithMany()
                        .HasForeignKey("SentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("SentUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorServer.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorServer.Data.Hobby", b =>
                {
                    b.Navigation("Favorite1Users");

                    b.Navigation("Favorite2Users");

                    b.Navigation("Favorite3Users");
                });
#pragma warning restore 612, 618
        }
    }
}
